root: NEU

neu:
  mode: active
  axis: 3x3
  inherits: none

dil.siz.ler:
  enabled: true
  source: /modules/dil-siz-ler/
  run: full

matrix:
  - [dil, siz, ler]
  - [rew, me,  for]
  - [gen, tol, ech]

echo:
  state: open
  return: true
